/* GENERALMNGRS */
export const GET_GENERALMNGRS = "GET_GENERALMNGRS"
export const GET_GENERALMNGRS_SUCCESS = "GET_GENERALMNGRS_SUCCESS"
export const GET_GENERALMNGRS_FAIL = "GET_GENERALMNGRS_FAIL"

/* GENERALMNGRS DETAIL*/
export const GET_GENERALMNGR_DETAIL = "GET_GENERALMNGR_DETAIL"
export const GET_GENERALMNGR_DETAIL_SUCCESS = "GET_GENERALMNGR_DETAIL_SUCCESS"
export const GET_GENERALMNGR_DETAIL_FAIL = "GET_GENERALMNGR_DETAIL_FAIL"

/**
 * add GENERALMNGR
 */
export const CREATE_GENERALMNGR = "CREATE_GENERALMNGR"
export const CREATE_GENERALMNGR_SUCCESS = "CREATE_GENERALMNGR_SUCCESS"
export const CREATE_GENERALMNGR_FAIL = "CREATE_GENERALMNGR_FAIL"

/**
 * Edit GENERALMNGR
 */
export const UPDATE_GENERALMNGR = "UPDATE_GENERALMNGR"
export const UPDATE_GENERALMNGR_SUCCESS = "UPDATE_GENERALMNGR_SUCCESS"
export const UPDATE_GENERALMNGR_FAIL = "UPDATE_GENERALMNGR_FAIL"

/**
 * Delete GENERALMNGR
 */
export const DELETE_GENERALMNGR = "DELETE_GENERALMNGR"
export const DELETE_GENERALMNGR_SUCCESS = "DELETE_GENERALMNGR_SUCCESS"
export const DELETE_GENERALMNGR_FAIL = "DELETE_GENERALMNGR_FAIL"
